# Orb Version 0.2.3

version: 2.1
description: A simple set of tools for managing orbs by Artsy

executors:
  orb-scripts:
    docker:
      - image: artsy/orb-scripts@latest

commands:
  setup-paths:
    steps:
      - run:
          name: Set orb scripts path
          command: |
            if [ ! -d "./scripts" ]; then 
              ln -s /tmp/orb-scripts scripts
            fi

jobs:
  publish:
    executor: orb-scripts
    parameters:
      namespace:
        description: CircleCI orb namespace
        type: string
    steps:
      - checkout
      - setup-paths
      - run:
          name: Install slack notifier
          command: |
            curl --location --output ./slack \
            https://github.com/cloudposse/slack-notifier/releases/download/0.2.0/slack-notifier_linux_amd64
            chmod +x ./slack
      - run:
          name: Publish orbs
          command: NAMESPACE=<< parameters.namespace >> scripts/publish_orbs.sh
