# Orb Version 0.7.0

version: 2.1
description: A simple set of tools for managing orbs by Artsy

executors:
  orb-scripts:
    docker:
      - image: artsy/orb-scripts
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

commands:
  check-for-env-vars:
    parameters:
      env-vars:
        description: Comma separated list of environment variables to check for. No spaces.
        type: string
    steps:
      - run:
          name: Check for environment variables
          command: |
            # Skip Forks
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Skipping, forks won't have the right env vars anyway."
              exit 0
            fi
            #Print the split string
            for env in << parameters.env-vars >>; do
              if [ -z "$(printenv $env)" ]; then
                echo "The env var '$env' was expected to be set, but isn't. Set it and then try again."
                exit 1
              fi
            done
  skip-if-fork-or-not-pr:
    parameters:
      pr-skip-message:
        type: string
        default: Skipping because this isn't a pr build
      fork-skip-message:
        type: string
        default: Skipping because this is a fork
    steps:
      - run:
          name: Don't deploy canary if it's not a PR or if it's a fork
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "<< parameters.pr-skip-message >>"
              circleci-agent step halt
            fi

            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "<< parameters.fork-skip-message >>"
              circleci-agent step halt
            fi
  setup-paths:
    steps:
      - run:
          name: Set orb scripts path
          command: |
            if [ ! -d "./scripts" ]; then
              ln -s /tmp/orb-scripts scripts
            fi

jobs:
  validate:
    executor: orb-scripts
    parameters:
      namespace:
        description: CircleCI orb namespace
        type: string
    steps:
      - checkout
      - setup-paths
      - run:
          name: Validate orbs
          command: NAMESPACE=<< parameters.namespace >> scripts/validate_orbs.sh
  publish:
    executor: orb-scripts
    parameters:
      namespace:
        description: CircleCI orb namespace
        type: string
    steps:
      - checkout
      - setup-paths
      - run:
          name: Install slack notifier
          command: |
            curl --location --output ./slack \
            https://github.com/cloudposse/slack-notifier/releases/download/0.2.0/slack-notifier_linux_amd64
            chmod +x ./slack
      - run:
          name: Publish orbs
          command: NAMESPACE=<< parameters.namespace >> scripts/publish_orbs.sh
