# Orb Version 0.1.19

version: 2.1
description: >
  Execute Docker build via Artsy-managed Docker daemon with a Circle CI fallback

executors:
  deploy:
    docker:
      - image: artsy/hokusai:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
  beta:
    docker:
      - image: artsy/hokusai:beta
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

commands:
  setup-artsy-remote-docker:
    parameters:
      artsy_docker_host:
        type: string
      artsy_docker_port:
        type: integer
      artsy_s3_path_root:
        type: string
    steps:
      - run:
          name: Setup Artsy Remote Docker Connection
          command: |
            if [[ -n "$AWS_ACCESS_KEY_ID" && -n "$AWS_SECRET_ACCESS_KEY" ]]; then
              printf "%s Setting up remote docker connection...\n" "$(TZ=UTC date)"
              mkdir ~/.docker
              aws s3 cp s3://<< parameters.artsy_s3_path_root >>/ca.pem ~/.docker/ca.pem
              aws s3 cp s3://<< parameters.artsy_s3_path_root >>/cert.pem ~/.docker/cert.pem
              aws s3 cp s3://<< parameters.artsy_s3_path_root >>/key.pem ~/.docker/key.pem

              echo 'export DOCKER_HOST="tcp://<< parameters.artsy_docker_host >>:<< parameters.artsy_docker_port >>"' >> "$BASH_ENV"
              echo 'export DOCKER_TLS_VERIFY="1"' >> "$BASH_ENV"
              source "$BASH_ENV"

              printf "Checking remote docker connection...\n"
              if docker ps --last 1 --quiet; then
                printf "Remote docker connection established.\n"
              else
                printf "Remote docker daemon unavailable. Reverting back to Circle CI docker.\n"
                rm $BASH_ENV
                exit 0
              fi
            else
              printf 'Required environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` unavailable. Reverting back to Circle CI docker.\n'
              exit 0
            fi

  buildkit-build-image-via-artsy:
    steps:
      - run:
          name: Build via Artsy Remote Docker Connection (Buildkit)
          no_output_timeout: 15m
          command: |
            if test -f "$BASH_ENV"; then
              source $BASH_ENV

              export DOCKER_BUILDKIT=1
              export BUILDKIT_PROGRESS=plain
              export COMPOSE_DOCKER_CLI_BUILD=1
              export HOKUSAI_ALWAYS_VERBOSE=1

              export TAG_LABEL=""
              if [ ! -z "${BUILD_TARGET}" ]; then
                TAG_LABEL="-${BUILD_TARGET}"
              fi
              export BUILD_TAG="${CIRCLE_SHA1}${TAG_LABEL}"

              printf "%s Building image...\n" "$(TZ=UTC date)"
              BUILD_TARGET="$BUILD_TARGET" BUILD_TAG="${BUILD_TAG}" hokusai build
              printf "%s Image built.\n" "$(TZ=UTC date)"

              printf "Skipping local docker build fallback...\n"
            fi
            circleci step halt

  buildkit-push-image-via-artsy:
    steps:
      - run:
          name: Push via Artsy Remote Docker Connection (Buildkit)
          no_output_timeout: 15m
          command: |
            if test -f "$BASH_ENV"; then
              source $BASH_ENV

              export DOCKER_BUILDKIT=1
              export BUILDKIT_PROGRESS=plain
              export COMPOSE_DOCKER_CLI_BUILD=1
              export HOKUSAI_ALWAYS_VERBOSE=1

              export TAG_LABEL=""
              if [ ! -z "${BUILD_TARGET}" ]; then
                TAG_LABEL="-${BUILD_TARGET}"
              fi
              export BUILD_TAG="${CIRCLE_SHA1}${TAG_LABEL}"

              if hokusai registry images --limit 1000 | grep -q $CIRCLE_SHA1; then
                echo "Skipping push as the tag $BUILD_TAG already exists in the Docker registry"
              else
                printf "%s Pushing image...\n" "$(TZ=UTC date)"
                hokusai registry push \
                  --no-build \
                  --local-tag="${BUILD_TAG}" \
                  --tag="${BUILD_TAG}" \
                  --skip-latest
                printf "%s Image pushed.\n" "$(TZ=UTC date)"
              fi

              printf "Skipping local docker build fallback...\n"
            fi
            circleci step halt

  build-image-via-artsy:
    steps:
      - run:
          name: Build & Push via Artsy Remote Docker Connection
          no_output_timeout: 15m
          command: |
            if test -f "$BASH_ENV"; then
              source $BASH_ENV

              printf "%s Building image...\n" "$(TZ=UTC date)"
              BUILD_TARGET="$BUILD_TARGET" BUILD_TAG="$CIRCLE_SHA1" hokusai build
              printf "%s Image built.\n" "$(TZ=UTC date)"

              if hokusai registry images --limit 1000 | grep -q $CIRCLE_SHA1; then
                echo "Skipping push as the tag $CIRCLE_SHA1 already exists in the Docker registry"
              else
                printf "%s Pushing image...\n" "$(TZ=UTC date)"
                hokusai registry push \
                  --no-build \
                  --local-tag="$CIRCLE_SHA1" \
                  --tag="$CIRCLE_SHA1" \
                  --skip-latest
                printf "%s Image pushed.\n" "$(TZ=UTC date)"
              fi

              printf "Skipping local docker build fallback...\n"
              circleci step halt
            else
              printf "Remote docker build unavailable. Reverting back to Circle CI docker.\n"
            fi

  build-image-via-circle:
    steps:
      - run:
          name: Build & Push via Circle CI Fallback
          no_output_timeout: 15m
          command: |
            printf "%s Building image...\n" "$(TZ=UTC date)"
            BUILD_TARGET="$BUILD_TARGET" BUILD_TAG="$CIRCLE_SHA1" hokusai build
            printf "%s Image built.\n" "$(TZ=UTC date)"

            if hokusai registry images --limit 1000 | grep -q $CIRCLE_SHA1; then
              echo "Skipping push as the tag $CIRCLE_SHA1 already exists in the Docker registry"
            else
              printf "%s Pushing image...\n" "$(TZ=UTC date)"
              hokusai registry push \
                --no-build \
                --local-tag="$CIRCLE_SHA1" \
                --tag="$CIRCLE_SHA1" \
                --skip-latest
              printf "%s Image pushed.\n" "$(TZ=UTC date)"
            fi

  test:
    steps:
      - run: hokusai registry pull --tag "$CIRCLE_SHA1"
      - run:
          name: Test
          command: hokusai test --no-build
          no_output_timeout: 3600s

jobs:
  test:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - test

  build:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
      artsy_docker_host:
        type: string
        default: docker.artsy.net
      artsy_docker_port:
        type: integer
        default: 2376
      artsy_s3_path_root:
        type: string
        default: artsy-dockerd
    steps:
      - add_ssh_keys
      - checkout
      - setup-artsy-remote-docker:
          artsy_docker_host: << parameters.artsy_docker_host >>
          artsy_docker_port: << parameters.artsy_docker_port >>
          artsy_s3_path_root: << parameters.artsy_s3_path_root >>
      - build-image-via-artsy
      - setup_remote_docker:
          version: 19.03.13
      - build-image-via-circle

  buildkit-build:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
      artsy_docker_host:
        type: string
        default: docker.artsy.net
      artsy_docker_port:
        type: integer
        default: 2376
      artsy_s3_path_root:
        type: string
        default: artsy-dockerd
    steps:
      - add_ssh_keys
      - checkout
      - setup-artsy-remote-docker:
          artsy_docker_host: << parameters.artsy_docker_host >>
          artsy_docker_port: << parameters.artsy_docker_port >>
          artsy_s3_path_root: << parameters.artsy_s3_path_root >>
      - buildkit-build-image-via-artsy

  buildkit-push:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
      artsy_docker_host:
        type: string
        default: docker.artsy.net
      artsy_docker_port:
        type: integer
        default: 2376
      artsy_s3_path_root:
        type: string
        default: artsy-dockerd
    steps:
      - add_ssh_keys
      - checkout
      - setup-artsy-remote-docker:
          artsy_docker_host: << parameters.artsy_docker_host >>
          artsy_docker_port: << parameters.artsy_docker_port >>
          artsy_s3_path_root: << parameters.artsy_s3_path_root >>
      - buildkit-push-image-via-artsy
