# Orb Version 1.3.1

version: 2.1
description: Publish NPM packages and canary deployments with Intuit's Auto

orbs:
  yarn: artsy/yarn@4.0.0
  node: artsy/node@0.1.0
  auto: auto/release@0.2.3
  utils: artsy/orb-tools@dev:da826a2455c0d9f9ce31f71db9b0601e

jobs:
  # Publishes a package to NPM
  publish:
    executor: node/build
    environment:
      AUTO_VERSION: v9.27.2
    parameters:
      version:
        type: string
        default: v9.27.2
      args:
        type: string
        default: ""
    steps:
      - yarn/pre-release
      - auto/shipit

  # Publishes a canary package to npm
  publish-canary:
    executor: node/build
    environment:
      AUTO_VERSION: v9.27.2
    parameters:
      version:
        type: string
        default: v9.27.2
      args:
        type: string
        default: ""
    steps:
      - utils/skip-if-fork-or-not-pr:
          pr-skip-message: Skipping, only deploys canaries on PR builds
          fork-skip-message: Skipping, can't deploy canaries from a fork
      - yarn/pre-release
      - auto/canary
