# Orb Version 1.0.0

version: 2.1
description: An orb for working w/ intuit's auto

orbs:
  yarn: artsy/yarn@dev:94201cf9cd41b8b0d7441b5095ea044d
  node: artsy/node@0.1.0
  auto: auto/release@0.1.0

jobs:
  # Publishes a package to NPM
  publish:
    executor: node/build
    environment:
      AUTO_VERSION: v9.10.5
    parameters:
      version:
        type: string
        default: v9.10.5
      args:
        type: string
        default: ""
    steps:
      - yarn/pre-release
      - auto/shipit

  # Publishes a canary package to npm
  publish-canary:
    executor: node/build
    environment:
      AUTO_VERSION: v9.10.5
    parameters:
      version:
        type: string
        default: v9.10.5
      args:
        type: string
        default: ""
    steps:
      - yarn/pre-release
      - auto/canary
