# Orb Version 2.2.0

version: 2.1
description: Publish NPM packages and canary deployments with Intuit's Auto

orbs:
  yarn: artsy/yarn@5.1.3
  auto: auto/release@0.2.3
  utils: artsy/orb-tools@0.5.0

executors:
  node:
    docker:
      - image: cimg/node:14.18.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

jobs:
  # Publishes a package to NPM
  publish:
    executor: node
    environment:
      AUTO_VERSION: << parameters.version >>
    parameters:
      version:
        type: string
        default: v10.36.5
      args:
        type: string
        default: ""
    steps:
      - yarn/pre-release
      - auto/shipit:
        arguments: << parameters.args >>

  # Publishes a canary package to npm
  publish-canary:
    executor: node
    environment:
      AUTO_VERSION: << parameters.version >>
    parameters:
      version:
        type: string
        default: v10.36.5
      args:
        type: string
        default: ""
    steps:
      - utils/skip-if-fork-or-not-pr:
          pr-skip-message: Skipping, only deploys canaries on PR builds
          fork-skip-message: Skipping, can't deploy canaries from a fork
      - yarn/pre-release
      - auto/canary:
        arguments: << parameters.args >>
