# Orb Version 0.7.4

version: 2.1
description: Reusable hokusai tasks for managing deployments

executors:
  deploy:
    docker:
      - image: artsy/hokusai:0.5.11
  beta:
    docker:
      - image: artsy/hokusai:beta

commands:
  setup:
    steps:
      - add_ssh_keys
      - checkout

  setup-docker:
    steps:
      - setup
      - setup_remote_docker

  install-aws-iam-authenticator:
    parameters:
      uri:
        type: string
        default: "https://artsy-provisioning-public.s3.amazonaws.com/aws-iam-authenticator_0.4.0_linux_amd64"
    steps:
      - run:
          name: Install AWS IAM Authenticator
          command: |
            curl -L -o aws-iam-authenticator << parameters.uri >>
            chmod +x ./aws-iam-authenticator
            mv aws-iam-authenticator /usr/local/bin/

  configure-hokusai:
    parameters:
      configUri:
        type: string
        default: "https://artsy-provisioning-public.s3.amazonaws.com/hokusai/config-ci.yml"
    steps:
      - run:
          name: Configure Hokusai
          command: |
            mkdir -p ~/.hokusai
            curl -o ~/.hokusai/config.yml << parameters.configUri >>
            hokusai configure

  push-image:
    steps:
      - setup-docker
      - run:
          name: Push
          command: |
            set +euo pipefail
            if hokusai registry images --limit 1000 | grep -q $CIRCLE_SHA1; then
              echo "Skipping push as the tag $CIRCLE_SHA1 already exists in the Docker registry"
            else
              hokusai registry push --tag $CIRCLE_SHA1
            fi

  run-tests:
    parameters:
      filename:
        type: string
        default: ""
        description: The docker-compose yaml file to use
      flags:
        type: string
        default: ""
        description: Optional hokusai flags
    steps:
      - when:
          condition: << parameters.filename >>
          steps:
            - run:
                name: Test
                command: hokusai test -f << parameters.filename >> << parameters.flags >>
      - unless:
          condition: << parameters.filename >>
          steps:
            - run:
                name: Test
                command: hokusai test << parameters.flags >>

jobs:
  test:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
      filename:
        type: string
        default: ./hokusai/test.yml
        description: The docker-compose yaml file to use
      flags:
        type: string
        default: ""
        description: Optional hokusai flags
    steps:
      - setup-docker
      - run-tests:
          filename: << parameters.filename >>
          flags: << parameters.flags >>

  push:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
    steps:
      - push-image

  deploy-staging:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
      project-name:
        type: string
        description: The name of the project as it appears on github
      time-out:
        type: string
        description: How long to wait for shell output before timing out
        default: 20m
    steps:
      - setup
      - install-aws-iam-authenticator
      - configure-hokusai
      - run:
          name: Validate Kubernetes Yaml
          command: hokusai staging update --skip-checks --dry-run
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1 --update-config
          no_output_timeout: << parameters.time-out >>
      - run:
          name: Update Staging branch
          command: git push git@github.com:artsy/<< parameters.project-name >>.git $CIRCLE_SHA1:refs/heads/staging --force

  deploy-production:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
        default: deploy
      time-out:
        type: string
        description: How long to wait for shell output before timing out
        default: 20m
    steps:
      - setup
      - install-aws-iam-authenticator
      - configure-hokusai
      - run:
          name: Validate Kubernetes Yaml
          command: hokusai production update --skip-checks --dry-run
      - run:
          name: What's being deployed
          command: hokusai pipeline gitcompare --org-name artsy || true
      - run:
          name: Changes with migrations
          command: hokusai pipeline gitlog | grep migration || true
      - run:
          name: Deploy
          command: hokusai pipeline promote --update-config
          no_output_timeout: << parameters.time-out >>
