# Orb Version 0.1.0

version: 2.2
description: Reusable hokusai tasks for managing deployments

executors:
  deploy:
    docker:
      - image: artsy/hokusai:0.5.6

commands:
  setup:
    steps:
      - add_ssh_keys
      - checkout

  setup-docker:
    steps:
      - setup
      - setup_remote_docker

jobs:
  test:
    executor: deploy
    steps:
      - setup-docker
      - run:
          name: Test
          command: hokusai test
  push:
    executor: deploy
    steps:
      - setup-docker
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite

  deploy-staging:
    executor: deploy
    parameters:
      project-name:
        type: string
        description: The name of the project as it appears on github
      time-out:
        type: string
        description: How long to wait for shell output before timing out
        default: 20m
    steps:
      - setup
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Validate Kubernetes Yaml
          command: hokusai staging update --dry-run
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1 --update-config
          no_output_timeout: << parameters.time-out >>
      - run:
          name: Update Staging branch
          command: git push git@github.com:artsy/<< parameters.project-name >>.git $CIRCLE_SHA1:refs/heads/staging --force

  deploy-production:
    executor: deploy
    parameters:
      time-out:
        type: string
        description: How long to wait for shell output before timing out
        default: 20m
    steps:
      - setup
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Validate Kubernetes Yaml
          command: hokusai production update --dry-run
      - run:
          name: What's being deployed
          command: hokusai pipeline gitcompare --org-name artsy
      - run:
          name: Changes with migrations
          command: hokusai pipeline gitlog | grep migration || true
      - run:
          name: Deploy
          command: hokusai production deploy staging --update-config
          no_output_timeout: << parameters.time-out >>
