# Orb Version 0.1.5

version: 2.1
description: Common yarn commands

orbs:
  node: artsy/node@0.1.0
  queue: eddiewebb/queue@1.0.110

commands:
  # https://circleci.com/docs/2.0/caching/#basic-example-of-dependency-caching
  save_dependencies:
    steps:
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  # If there isn't a match to the first key, it'll do a partial match of the
  # second. That means after the first cache save there will always be a cache
  # hit, but it might be an older version of the cache
  #
  # https://circleci.com/docs/2.0/caching/#restoring-cache
  load_dependencies:
    steps:
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}

  # By default when yarn runs it does not check the filesystem to ensure the
  # packages it expects to be installed are actually installed. Using the
  # --check-files flag ensures that any packages or files missing or out of date
  # on the file system (i.e. those which might be restored from cache) match what
  # the yarn.lock file specifies
  install:
    steps:
      - run: yarn

  setup:
    steps:
      - checkout
      - load_dependencies
      - install

  update_dependencies:
    steps:
      - setup
      - save_dependencies

  run-script:
    parameters:
      script:
        type: string
    steps:
      - setup
      - run: yarn << parameters.script >>

  run-release:
    parameters:
      script:
        type: string
        default: yarn release
    steps:
      - add_ssh_keys
      - setup
      - run: git pull
      # Setup the .npmrc with the proper registry and auth token to publish
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: << parameters.script >>

jobs:
  run:
    executor: node/build
    parameters:
      script:
        type: string
    steps:
      - run-script:
          script: << parameters.script >>

  lint:
    executor: node/build
    steps:
      - run-script:
          script: lint

  relay:
    executor: node/build
    steps:
      - run-script:
          script: relay

  type-check:
    executor: node/build
    steps:
      - run-script:
          script: type-check

  test:
    executor: node/build
    parameters:
      args:
        type: string
        default: -w 4
    steps:
      # Runs jest tests with 6 concurrent workers. Without limiting it to 6
      # workers Jest will spawn many memory hungry workers and ultimately
      # starve the job for memory.
      - run-script:
          script: test << parameters.args >>

  update-cache:
    executor: node/build
    steps:
      - update_dependencies

  # A job responsible for ensuring only 1 master build runs at a time so that
  # there are no deployment race conditions
  workflow-queue:
    executor: node/build
    steps:
      - queue/until_front_of_line:
          time: "2" # how long a queue will wait until the job exits
          only-on-branch: master # restrict queueing to a specific branch (default *)
          consider-job: false # block whole workflow if any job still running

  release:
    executor: node/build
    steps:
      - run-release

  auto-release:
    executor: node/build
    steps:
      - run-release:
          script: npx auto shipit

  auto-pr-check:
    executor: node/build
    steps:
      - setup
      - run:
          name: Check if PR has valid labels
          command: |
            if [ ! -z "$CIRCLE_PR_NUMBER" ]; then
              npx --package auto-release-cli auto pr-check --pr $CIRCLE_PR_NUMBER --url $CIRCLE_PULL_REQUEST
            else
              npx --package auto-release-cli auto pr-check --pr ${CIRCLE_PULL_REQUEST##https:/*/} --url $CIRCLE_PULL_REQUEST
            fi
